### ISSUE TITLE
Unable to run the code 

### ISSUE THREAD

**Issue by stranger528** [prubbens/PhenoGMM#1]
Dear author,
I have problem in running the code in the jupyter notebook.
when I restart the kernel.  It happened that in the sixth block, it just turned out to be ln[*]

![1](https://user-images.githubusercontent.com/47015796/75158195-93639a80-5750-11ea-92ca-11687da0abd9.PNG)

I have tried to restart kernel, but the same problem continued to happen.
What's more, I have removed the whole code in pycharm, and it didn't give an result, just showed nothing...
![2](https://user-images.githubusercontent.com/47015796/75158369-e8071580-5750-11ea-951c-d0a14b68aa33.PNG)
could you explain why it happen?
Thanks!

**Comment by prubbens** [comment]
How long did you wait for the sixth block to run? It takes quite some time to finish this step (see note above).

**Comment by stranger528** [comment]
it was about seven minutes.&nbsp; your train set and test do not seem so large. they only have 200-300 for each. so I thought somehow there was something wrong&nbsp;



---Original---

**Comment by prubbens** [comment]
Indeed, but this is not the training set yet. What happens is the following: 
--> Inidividual populations are sampled according to predefined compositions (`comp_train` and `comp_test`). This takes quite some, it's been a while since I've run the code, but if I remember correctly about half an hour. 
--> Next you have a large dataframe of 2500 cells times 2 replicates times 300 train communities / or 100 test communities. To this dataframe you are going to fit a Gaussian Mixture Model (again, this takes some time). This you will use to extract cell counts per mixture and sample. 
--> Now you have your training set of 300 samples, to which you can fit your predictive model. 

I'd say, give it half an hour (or an hour to be sure), if it still doesn't work, we can look into it more in detail.

**Comment by stranger528** [comment]
thanks a lot for your answer I will try again

---Original---

**Comment by stranger528** [comment]
thanks author
The code is running well.&nbsp;



---Original---

**Comment by prubbens** [comment]
Great, let me know if you have other questions!

**Comment by stranger528** [comment]
Dear peter
&nbsp; I am the student of teacher Zizhon Qi.&nbsp; And there is a question I wish to know.&nbsp; So would you be pleased to answer.&nbsp;
I am running a program and try to sort cells' data collected by Flow cytometry.&nbsp;
Inspiring by your article， I also use Guass mixture model.&nbsp;&nbsp;
I let the training stops when there is one (maybe more) covariance mmatrix's determinat is zero.&nbsp;
I wish to know is it right? In my view when the determinat is zero then the covariance matrix is irreversible and the Guass model shall not exist.&nbsp;
And I also wonder at what circumstances do you stop the training.&nbsp;
Thanks for your answer and forgive my poor grammar.&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;yours sincerely
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Julius Yang





---Original---

**Comment by prubbens** [comment]
Hi Julius Yang, 

I don't use the determinant as stopping criterion for the Gaussian Mixture Model. I use the default settings from the scikit-learn machine learning library, which amounts to letting the algorithm stop after a certain number of EM iterations (`max_iter`), or when the convergence threshold (`tol`) of the EM algorithm is reached.  

I am confused by your comment: "I let the training stops when there is one (maybe more) covariance mmatrix's determinat is zero.&nbsp; I wish to know is it right? In my view when the determinat is zero then the covariance matrix is irreversible and the Guass model shall not exist.&nbsp;" Can you provide an explanation for it? 

Best, 

Peter

**Comment by stranger528** [comment]
Hi peter.&nbsp;
I simply explain your question.&nbsp;
The guass model can be written in the form of algebra-like(I just can not say it in English more accurately)which you can see in the picture.&nbsp;
and Sigma is the covariance matrix 。X is a vector.&nbsp;
if the determinat of Sigma is zero then the covariance is irreversible.&nbsp; And supposing there are K dimensions，and since the determinat is zero,&nbsp; which means there are at least two vectors are linearly dependent whenever your choose any D vectors from the space which is expended by the columns of Sigma.&nbsp; Then the dimension of the Sigma can never be D.&nbsp;
And we assume that the guass model of D dimension exists so the Sigma exists with D dimension.&nbsp; and now the determinat tells us the the Sigma doesn't exist, nor the guass model.&nbsp;
&nbsp;We are searching for the&nbsp; guass mix model with more than one guass models.&nbsp;
we don't know how many.&nbsp; I set a loop from k=2.&nbsp; at each time I run the program to get K Sigmas sif none of the deteminats is zero then, let the K=K+1 else export the case K-1
last, I apology for my poor grammars.&nbsp;
best
Julius Yang.&nbsp;

---Original---

**Comment by prubbens** [comment]
Okay, I think I understand your comment, could you maybe add your picture just to be sure?

**Comment by stranger528** [comment]
I also attached the picture at the last e-mail I sent.&nbsp; maybe something went wrong.&nbsp; when you receive&nbsp; this e-mail please check that the picture is attached at appendix.&nbsp;

---Original---

**Comment by prubbens** [comment]
Nope, no picture... Maybe you can directly add it here on the github repository?

**Comment by stranger528** [comment]
Dr.peter it seems I can not leave a picture here. I send it to your current email which your gave to my tutor Dr.Qi.

**Comment by prubbens** [comment]
I will write to you off-line, and post answer/solution here.
